name: Java CI (JDK 8)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Compile Java code
      run: |
        mkdir -p build
        javac -cp ".:lib/*" -d build $(find src -name "*.java") $(find test -name "*.java")

    - name: Run JUnit tests
      run: |
        java -cp "build:lib/*" org.junit.runner.JUnitCore kasir.HistoryTest
